### ISSUE TITLE
Cannot read property 'getUid' of undefined

### ISSUE THREAD

**Issue by Minishlink** [cometchat-pro/react-native-chat-sdk#28] opened 2021-03-25 05:30 UTC
### Describe the problem

Sometimes, we have this error popping up, it looks like this "user.getUid()" is called when you send a call to your ping analytics endpoint.

Here is the minified part :

```js
try {
              p.keyStore.get("deviceId").then(function (e) {
                var t = R.SDKHeader.platform,
                    n = "",
                    s = e,
                    o = {
                  version: R.SDKHeader.sdkVersion,
                  apiVersion: R.APPINFO.apiVersion,
                  origin: t,
                  uts: new Date().getTime()
                };
                g.isFalsy(c.resource) || (o.resource = c.resource), g.isFalsy(c.platform) || (o.platform = c.platform), g.isFalsy(c.language) || (o.language = c.language), navigator && (n = navigator.userAgent);
                var r = {
                  appInfo: o,
                  uid: p.user.getUid(),
                  userAgent: n,
                  deviceId: s,
                  platform: R.SDKHeader.platform
                };
                g.isFalsy(p.getSessionId()) || (r.wsId = p.getSessionId()), p.analyticsHost || (p.analyticsHost = g.format(R.ANALYTICS.analyticsHost, p.appSettings.getRegion())), p.analyticsVersion || (p.analyticsVersion = R.ANALYTICS.analyticsVersion);
                var i = "https://" + p.analyticsHost + "/" + p.analyticsVersion + "/ping",
                    a = {
                  appId: p.appId,
                  sdk: g.format(R.SDKHeader.sdk, R.SDKHeader.platform, R.SDKHeader.sdkVersion),
                  "Content-Type": "application/json"
                };
                p.settingsHash && (a.settingsHash = p.settingsHash), p.settingsHashReceivedAt && (a.settingsHashReceivedAt = p.settingsHashReceivedAt), p.jwt && (a.Authorization = "Bearer " + p.jwt), p.authToken && (a.authToken = p.authToken), S.postData(i, "POST", r, a, !1).then(function (e) {
                  return e.json();
                }).then(function (e) {
                  if (e.hasOwnProperty(R.ResponseConstants.RESPONSE_KEYS.KEY_DATA)) g.Logger.log("Analytics Ping Request Data", e[R.ResponseConstants.RESPONSE_KEYS.KEY_DATA]);else if (e.hasOwnProperty(R.ResponseConstants.RESPONSE_KEYS.KEY_ERROR)) {
                    var t = e[R.ResponseConstants.RESPONSE_KEYS.KEY_ERROR];
                    g.Logger.log("Analytics Ping Request Error", new C.CometChatException(t));
                    var n = t.code;

                    if (n === R.Errors.ERR_SETTINGS_HASH_OUTDATED) {
                      var s = p.authToken;
                      p.logout().then(function () {
                        p.login(s);
                      });
                    }

                    n === R.Errors.ERR_NO_AUTH && c.updateJWT();
                  }
                }).catch(function (e) {
                  g.Logger.error("CometChat: pingAnalytics Fetch Error", e);
                });
              });
            } catch (e) {
              g.Logger.error("CometChat: pingAnalytics", e);
            }
```

You can  see that user can be null, and also your catch cannot catch the promise error since you don't await the promise...

Using last version.

**Comment by mayur-bhandari** [comment] 2021-03-25 06:01
Hello @Minishlink,

We are unable to reproduce the issue at our end. Can you please share the steps to reproduce the issue?

**Comment by Minishlink** [comment] 2021-03-25 06:30
Hello @mayur-bhandari, this is clearly a race condition so I cannot give you any clear reproduction steps.
It might be way easier to debug if you had the sources on this repo by the way

**Comment by proveshapyne** [comment] 2022-01-15 07:26
Hello @Minishlink,

We had reached out to you over email regarding this issue and therefore, I am closing out this ticket. Please write to us at help@cometchat.com if you need any further technical help.
Thank you.

Regards,
Provesha

**Closed as completed** 2024-04-05 09:39 UTC
